services:

  mongo:
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # MongoDBの管理者のユーザー名
      MONGO_INITDB_ROOT_PASSWORD: admin123 # MongoDBの管理者のパスワード
    image: mongo:6.0
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - ./volumes/data:/data/db

networks:
  app_network:
    driver: bridge

