services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - app_network

  mongo:
    container_name: mongo
    image: mongo:6.0
    ports:
      - "27017:27017"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data: